version: "3"
services:
  bot:
    image: bot_image
    build:
        context: ./bot
    environment:
      - TOKEN=${TOKEN}
      - RM_HOST=${RM_HOST}
      - RM_PORT=${RM_PORT}
      - RM_USER=${RM_USER}
      - RM_PASSWORD=${RM_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
    networks:
      custom_network:
        ipv4_address: 172.20.0.100
    volumes:
      - pg_logs:/repl_logs/
    container_name: "${BOT}"
  db:
    image: db_image
    build: ./db
    volumes:
      - pg_logs:/var/log/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
      - DB_REPL_HOST=${DB_REPL_HOST}.my_network
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
    container_name: "${DB_HOST}"
    networks:
      custom_network:
        ipv4_address: 172.20.0.101
  db_repl:
    image: db_repl_image
    build: ./db_repl
    container_name: "${DB_REPL_HOST}"
    environment:
      - DB_HOST=${DB_HOST}.my_network
      - DB_PORT=${DB_PORT}
      - DB_REPL_HOST=${DB_REPL_HOST}
      - DB_REPL_PORT=${DB_REPL_PORT}
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
    networks:
      custom_network:
        ipv4_address: 172.20.0.102
volumes:
  pg_data:
  pg_logs:
  
networks:
  custom_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24