version: "3.1"
services:
  bot:
    image: bot_image
    env_file:
      - .env
    volumes:
      - repl_logs:/repl_logs
    networks:
      custom_network:
        ipv4_address: 172.20.0.100

  db:
    image: db_image
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
      - DB_REPL_HOST=${DB_REPL_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - repl_logs:/var/log/postgresql
    networks:
      custom_network:
        ipv4_address: ${DB_HOST}
        
  db_repl:
    image: db_repl_image
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_REPL_HOST=${DB_REPL_HOST}
      - DB_REPL_PORT=${DB_REPL_PORT}
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
    depends_on:
      - db    
    networks:
      custom_network:
        ipv4_address: ${DB_REPL_HOST}

volumes:
  repl_logs:

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet:  172.20.0.0/24